#!/bin/bash
# Sequential (reference chaining). nano_banana_pro 9:16 2k, 2cr each.
STYLE="Bold flat 2D vector illustration, thick clean outlines, flat even color, no gradients, no rendered lighting, no text, no letters, no numbers, no people. Palette strictly: deep red #C8102E, near-black #111111, warm off-white #F5F0E6, mid grey #9AA0A6."
g(){ local n=$1; shift; local ref=$1; shift; local p="$*"
  local args=(generate create nano_banana_pro --prompt "$STYLE $p" --aspect-ratio 9:16 --resolution 2k --wait --wait-timeout 6m --wait-interval 5s)
  [ -n "$ref" ] && [ "$ref" != "-" ] && args+=(--image-references "build/assets/$ref.png")
  local out; out=$(higgsfield "${args[@]}" 2>&1); local u=$(echo "$out" | grep -o 'https://[^ ]*' | tail -1)
  if [ -n "$u" ]; then curl -sS -f -o "build/assets/$n.png" "$u" && echo "$n OK"; else echo "$n FAIL: $(echo "$out"|tail -1)"; fi
}
g B3A - "Technical diagram cutaway on a warm off-white engineering plate with thin ruled corner marks: a chrome-grey P-trap and drain pipe sliced open lengthwise, near-black pipe walls. Interior walls coated with a THIN ring of dark buildup drawn as layered tree-ring growth bands, near-black with deep red striations; a WIDE open grey water channel through the middle. Two clean thin leader lines run from the buildup to small empty rectangular label plates near the frame edge."
g B3B B3A "Identical technical diagram cutaway, identical framing, identical plate and leader lines and empty label plates: the ONLY change is the tree-ring buildup now grown THICK and layered, filling most of the pipe, the grey water channel narrowed to a thin sliver."
g B4 B3B "Split composition. Top half: a near-black kitchen sink basin in side profile, brim-full of still mid-grey water, waterline at the rim, no swirl. Bottom half: the same cutaway plate with the pipe now FULLY blocked wall-to-wall by the dark tree-ring mass with red striations, grey water stacked behind it, three flat deep-red chevron arrows pointing upward toward the floor line, a thin red vignette at the frame edges."
g B5 B3A "Tall composition. Upper two-thirds: the same technical cutaway plate with the pipe interior COMPLETELY CLEAN and open, bright warm off-white channel with smooth flat horizontal grey flow lines running full width, no buildup at all, leader lines pointing at clear pipe. Lower third: a small flat deep-red service van silhouette with a tiny roof light-bar on a near-black road line under a flat off-white crescent moon on near-black night sky. The van is unmarked, no logos."
g B2 B3A "One tall vertical composition for a downward pan. Top third: a near-black sink basin in side profile on a warm off-white counter, mid-grey standing water with one lazy swirl line over the drain mouth. A straight near-black drain pipe runs straight down the middle of the frame through a flat floor line. Bottom third: the same engineering-plate cutaway of the pipe sliced open, thin tree-ring buildup with red striations inside, grey channel open, one leader line to an empty label plate."
g B1 - "Top-down view of a warm off-white kitchen sink basin filling most of the frame against a near-black surround. A shallow pool of pale grey standing water with ONE single lazy spiral line over the near-black circular drain opening. Three thin deep-red concentric ripple rings radiate outward from the drain like a target, bold and graphic at thumbnail size."
